#include "hal_data.h"
#include "stdio.h"
#include "SEGGER_RTT.h"
#include "perf_counter.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

__attribute__((section(".dtcm_data")))
volatile char data_out[256] = {0};
/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */

    SEGGER_RTT_Init();
    init_cycle_counter(false);

    printf("Hello CKPCOR-RA8D1! \r\n");
    
    uint64_t dwInstructions = perfc_pmu_get_instruction_count();
    uint32_t dwInsCalib = perfc_pmu_get_instruction_count() - dwInstructions;
    int64_t lCycles = 0;
    
    dwInstructions = perfc_pmu_get_instruction_count();
    
    __cycleof__("Coremark", { lCycles = __cycle_count__; }) {
#ifdef __PERF_COUNTER_COREMARK__
    coremark_main();
#endif
    }
    dwInstructions = perfc_pmu_get_instruction_count() - dwInstructions - dwInsCalib;
    
    printf( "\r\n"
            "No. Instrunctions: %lld\r\n"
            "Cycle Used: %lld\r\n"
            "Cycles per Instructions: %3.3f \r\n", 

            dwInstructions,
            lCycles,
            (double)lCycles / (double)dwInstructions);
    

    while(1) {
        delay_ms(1000ul);
        printf("[%016llx]", get_system_ticks());
        printf("%lld\r\n", get_system_ms());
    }
    
#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart (bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        IOPORT_CFG_OPEN(&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
